// <auto-generated />
namespace EF_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ContactDB_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactDB_init));
        
        string IMigrationMetadata.Id
        {
            get { return "202302210003559_ContactDB_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
